#ifndef KALMAN_PROTOCOL_STATUS_REPORT_COMMON_H_
#define KALMAN_PROTOCOL_STATUS_REPORT_COMMON_H_

#include <stdint.h>

#define KALMAN_PROTOCOL_STATUS_REPORT_ID_BYTES 2

typedef enum {
    OK,
    WARNING,
    CRITICAL,
} StatusReportResult_TypeDef;

#endif // KALMAN_PROTOCOL_STATUS_REPORT_COMMON_H_